perf: 提交部分代码

diff --git a/scripts/git-hooks/commit-msg b/scripts/git-hooks/commit-msg
--- a/scripts/git-hooks/commit-msg
+++ b/scripts/git-hooks/commit-msg
@@ -1,46 +1,142 @@
-#!/bin/sh
+#!/bin/bash
+# From Gerrit Code Review 2.13.5
+# 12333
+# Part of Gerrit Code Review (https://www.gerritcodereview.com/)
 #
-# this is a bash shell to check the commit msg. If you DO NOT follow the convention we defined, it can not be commit success.
-# Please see the detail convention in https://git.mail.netease.com/tech/yxguidelines/yanxuan-git-commit-msg-convention
+# Copyright (C) 2009 The Android Open Source Project
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+# http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
 
-export LANG=zh_CN.UTF-8
+unset GREP_OPTIONS
 
-types="(feat|change|fix|docs|style|refactor|test|chore|revert)"
-commit_regex="(^$types(\([^\)]*\))?:.{1,50}$)|^(Merge|Revert)"
+CHANGE_ID_AFTER="Bug|Issue|Test|Feature|Fixes|Fixed"
+MSG="$1"
 
-error_msg="Aborting commit. Please follow the convention.
 
-<type>(<scope>): <subject>
 
-<body>
+function print_hint() {
+    echo "
+错误 >>> 请求参照标准格式: <type>[optional scope][!|?]: <description>
+错误 >>> 或者参考 wiki: http://wiki.bigo.sg:8090/pages/viewpage.action?pageId=115737742"
 
-<footer>
+}
+## 检查 commit 信息的格式.
+firstLine=`head -n 1 "$MSG"`
 
-scope.size <= 20
-subject.size <= 50
-
-Scope 的定义大的模块，比如（登录，网络库，蓝牙框架等），可以省略，但是 subject 一定需要遵循 WBO 的原则。在 scope 存在时，原则就是 scope 指定大的模块，subject 中的 where 指定具体的页面。
-
-Type（重要）必须选填以下中的一个：
-
-feat: 新功能（feature）
-change: 对原提交的修改，如新功能提交之后的优化、影响较小的代码重构等
-fix: 修补bug
-docs: 文档（documentation）
-style: 格式（不影响代码运行的变动）
-refactor: 重构（即不是新增功能，也不是修改bug的代码变动）
-test: 增加测试
-chore: 构建过程或辅助工具的变动
-revert: 回滚
-例如：
----
-revert: feat(pencil): add 'graphiteWidth' option
-
-This reverts commit 667ecc1654a317a13331b17617d973392f415f02.
----
-see the detail in https://git.mail.netease.com/Fly/yanxuan-git-commit-msg-convention."
-
-if ! grep -qE "$commit_regex" "$1"; then
-    echo "$error_msg" >&2
+if [[ -z "$firstLine" ]];
+then
+    echo "commit fail, first line of commit message can not be empty."
     exit 1
 fi
+
+# 忽略 merge 类型的提交
+echo "$firstLine" | grep -i -E "^(merge|revert)" 1>/dev/null
+
+if [[ $? -eq 0 ]];
+then
+    exit 0
+fi
+
+echo "提交的首行为:"
+echo "    $firstLine"
+echo
+
+types="(fix|story|feat|perf|refactor|style|docs|i18n|test|stat|chore)"
+scopes="(ad|detail|flutter|live|login|im|index|media|news|prod|push|share|search)"
+
+# 尝试识别 type
+if ! echo "$firstLine" | grep -E "^[a-zA-Z0-9]+" 1>/dev/null
+then
+    echo "错误 >>> 无法识别提交的类型."
+    print_hint
+    exit 1
+fi
+
+# 提取 type 并判断是否合法
+type=`echo "$firstLine" | sed -E -e "s/^([a-zA-Z0-9]+).*/\1/g"`
+
+if ! echo "$type" | grep -E "^$types" 1>/dev/null
+then
+    echo "错误 >>> \"$type\" 不是合法的类型"
+    print_hint
+    exit 1
+fi
+
+# 判断是否有 scope
+if echo "$firstLine" | grep -E "^$types(\(.*\))" 1>/dev/null
+then
+    # 提取 scope 并检查是否合法
+    scope=`echo "$firstLine" | sed -E -e "s/^$types\((.*)\).*/\2/g"`
+    if [[ -z ${scope} ]];
+    then
+        echo "错误 >>> 提交范围不能为空"
+        print_hint
+        exit 1
+    fi
+    if ! echo "$scope" | grep -E "^$scopes" 1>/dev/null
+    then
+        echo "错误 >>> \"$scope\" 不是合法的范围"
+        print_hint
+        exit 1
+    fi
+fi
+
+if ! echo "$firstLine" | grep -E "^$types(\($scopes\))?(\?|\!)?:." 1>/dev/null
+then
+    space=`echo "$firstLine" | sed -E -e "s/^$types(\($scopes\))?(\?|\!)?:(.).*/\5/g"`
+    if [[ ${space} != " " ]];
+    then
+        echo "错误 >>> \":\" 后面必须要有空格"
+        print_hint
+        exit 1
+    fi
+fi
+
+if ! echo  "$firstLine" | grep -E "^$types(\($scopes\))?(\?|\!)?: " 1>/dev/null
+then
+    echo "错误 >>> 格式错误."
+    print_hint
+    exit 1
+fi
+
+if ! echo "$firstLine" | grep -E "^$types(\($scopes\))?(\?|\!)?: .{6}" 1>/dev/null
+then
+    echo "错误 >>> 首行太短, 至少需要 6 个字符."
+    print_hint
+    exit 1
+fi
+
+if ! echo "$firstLine" | grep -E "^$types(\($scopes\))?(\?|\!)?: .{6,60}$" 1>/dev/null
+then
+    echo "错误 >>> 首行太长, 最多只能 60 字符."
+    print_hint
+    exit 1
+fi
+
+lineCount=`cat "$MSG" | wc -l | sed -e 's/^[[:space:]]*//'`
+if [[ ${lineCount} -eq 1 ]]; then
+    exit 0
+fi
+
+secondLine=`head -n 2 "$MSG" | tail -n 1 | sed -e 's/^[[:space:]]*//'`
+if [[ -n "$secondLine" ]];
+then
+    echo "错误 >>> 第二行必须为空"
+    print_hint
+    exit 1
+fi
+
+exit 0
+
+
